#!/bin/bash

while true
do

#Logo
echo "================================="
echo " ██████╗ ███████╗ █████╗ ██████╗ "
echo "██╔════╝ ██╔════╝██╔══██╗██╔══██╗"
echo "██║  ███╗█████╗  ███████║██████╔╝"
echo "██║   ██║██╔══╝  ██╔══██║██╔══██╗"
echo "╚██████╔╝███████╗██║  ██║██║  ██║"
echo " ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝"
echo "================================="
echo -e "https://www.gear-tech.io/"
echo "================================="

# Menu
PS3='Select an action: '
options=(
"Install and run Node"
"Restart Node"
"Log Node"
"Update"
"Update with purge-chain"
"Delete Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in

"Install and run Node")
echo "================================="
echo "Write the name of your node"
echo "================================="
read GEARNODENAME
echo 'export GEARNODENAME='$GEARNODENAME >> $HOME/.bash_profile
source ~/.bash_profile

wget https://get.gear.rs/gear-nightly-linux-x86_64.tar.xz && \
tar xvf gear-nightly-linux-x86_64.tar.xz && \
rm gear-nightly-linux-x86_64.tar.xz

sudo tee <<EOF >/dev/null /etc/systemd/system/gear-node.service
[Unit]
Description=Gear Node
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/
ExecStart=/root/gear --name '$GEARNODENAME' --telemetry-url 'ws://telemetry-backend-shard.gear-tech.io:32001/submit 0'
Restart=always
RestartSec=3
LimitNOFILE=10000

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl restart systemd-journald
sudo systemctl daemon-reload
sudo systemctl enable gear-node
sudo systemctl restart gear-node
break
;;

"Delete Node")
sudo systemctl stop gear-node
sudo systemctl disable gear-node
sudo rm -rf /root/.local/share/gear-node
sudo rm /etc/systemd/system/gear-node.service
sudo rm /root/gear
break
;;

"Log Node")
journalctl -u gear-node -n 50
break
;;

"Update")
sudo systemctl stop gear-node
wget https://get.gear.rs/gear-nightly-linux-x86_64.tar.xz
tar xvf gear-nightly-linux-x86_64.tar.xz
rm gear-nightly-linux-x86_64.tar.xz
sudo systemctl restart gear-node
break
;;

"Update with purge-chain")
sudo systemctl stop gear-node
/root/gear purge-chain -y
wget https://get.gear.rs/gear-nightly-linux-x86_64.tar.xz
tar xvf gear-nightly-linux-x86_64.tar.xz
rm gear-nightly-linux-x86_64.tar.xz
sudo systemctl restart gear-node
break
;;

"Restart Node")
sudo systemctl restart gear-node
break
;;

"Exit")
exit
;;
*) echo "invalid option $REPLY";;
esac
done
done
