#!/bin/bash

while true
do

#Logo
echo "================================="
echo " ██████╗ ███████╗ █████╗ ██████╗ "
echo "██╔════╝ ██╔════╝██╔══██╗██╔══██╗"
echo "██║  ███╗█████╗  ███████║██████╔╝"
echo "██║   ██║██╔══╝  ██╔══██║██╔══██╗"
echo "╚██████╔╝███████╗██║  ██║██║  ██║"
echo " ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝"
echo "================================="
echo -e "https://www.gear-tech.io/"
echo "================================="

# Menu
PS3='Select an action: '
options=(
"Install and run Node"
"Restart Node"
"Log Node"
"Update"
"Update with purge-chain 25.03.23"
"Delete Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in

"Install and run Node")
echo "================================="
echo "Write the name of your node"
echo "================================="
read GEARNODENAME
echo 'export GEARNODENAME='$GEARNODENAME >> $HOME/.bash_profile
source ~/.bash_profile

wget https://get.gear.rs/gear-nightly-linux-x86_64.tar.xz && \
sudo tar -xvf gear-nightly-linux-x86_64.tar.xz -C /usr/bin && \
rm gear-nightly-linux-x86_64.tar.xz
sudo cp gear /usr/bin

sudo tee <<EOF >/dev/null /etc/systemd/system/gear-node.service
[Unit]
Description=Gear Node
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/
ExecStart=/usr/bin/gear --name '$GEARNODENAME' --telemetry-url 'ws://telemetry-backend-shard.gear-tech.io:32001/submit 0'
Restart=always
RestartSec=3
LimitNOFILE=10000

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl restart systemd-journald
sudo systemctl daemon-reload
sudo systemctl enable gear-node
sudo systemctl restart gear-node
echo -e "\n\033[32m ================================= \033[0m"
echo -e "\n\033[32m Node installation completed \033[0m"
echo -e "\n\033[32m ================================= \033[0m"
break
;;

"Delete Node")
sudo systemctl stop gear-node
sudo systemctl disable gear-node
sudo rm -rf /root/.local/share/gear-node
sudo rm /etc/systemd/system/gear-node.service
sudo rm /root/gear
echo -e "\n\033[32m ================================= \033[0m"
echo -e "\n\033[32m Node deletion completed \033[0m"
echo -e "\n\033[32m ================================= \033[0m"
break
;;

"Log Node")
journalctl -u gear-node -fn 30
break
;;

"Update")
sudo systemctl stop gear-node
wget https://get.gear.rs/gear-nightly-linux-x86_64.tar.xz
sudo tar -xvf gear-nightly-linux-x86_64.tar.xz -C /usr/bin
rm gear-nightly-linux-x86_64.tar.xz
sudo systemctl restart gear-node
sleep 45
sudo systemctl stop gear-node
sudo cp /root/.local/share/gear/chains/gear_staging_testnet_v6/network/secret_ed25519 /root/.local/share/gear/chains/gear_staging_testnet_v7/network/secret_ed25519
sudo systemctl restart gear-node
echo -e "\n\033[32m ================================= \033[0m"
echo -e "\n\033[32m Node update completed \033[0m"
echo -e "\n\033[32m ================================= \033[0m"
break
;;

"Update with purge-chain 25.03.23")
sudo systemctl stop gear-node
/root/gear purge-chain -y
rm -rvf /root/.local/share/gear/chains/gear_staging_testnet_v5/db
wget https://get.gear.rs/gear-nightly-linux-x86_64.tar.xz
sudo tar -xvf gear-nightly-linux-x86_64.tar.xz -C /usr/bin
rm gear-nightly-linux-x86_64.tar.xz
sudo systemctl restart gear-node
sleep 45
sudo systemctl stop gear-node
sudo cp /root/.local/share/gear/chains/gear_staging_testnet_v6/network/secret_ed25519 /root/.local/share/gear/chains/gear_staging_testnet_v7/network/secret_ed25519
sudo systemctl restart gear-node
echo -e "\n\033[32m ================================= \033[0m"
echo -e "\n\033[32m Node update completed \033[0m"
echo -e "\n\033[32m ================================= \033[0m"
break
;;

"Restart Node")
sudo systemctl restart gear-node
echo -e "\n\033[32m ================================= \033[0m"
echo -e "\n\033[32m Node restarted \033[0m"
echo -e "\n\033[32m ================================= \033[0m"
break
;;

"Exit")
exit
;;
*) echo "invalid option $REPLY";;
esac
done
done
